// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: proto/rates/v1/rates.proto

package ratesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strategy      string                 `protobuf:"bytes,1,opt,name=strategy,proto3" json:"strategy,omitempty"` // topN | avgNM
	N             int32                  `protobuf:"varint,2,opt,name=n,proto3" json:"n,omitempty"`
	M             int32                  `protobuf:"varint,3,opt,name=m,proto3" json:"m,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatesRequest) Reset() {
	*x = GetRatesRequest{}
	mi := &file_proto_rates_v1_rates_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatesRequest) ProtoMessage() {}

func (x *GetRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rates_v1_rates_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatesRequest.ProtoReflect.Descriptor instead.
func (*GetRatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_rates_v1_rates_proto_rawDescGZIP(), []int{0}
}

func (x *GetRatesRequest) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *GetRatesRequest) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *GetRatesRequest) GetM() int32 {
	if x != nil {
		return x.M
	}
	return 0
}

type GetRatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ask           string                 `protobuf:"bytes,1,opt,name=ask,proto3" json:"ask,omitempty"`
	Bid           string                 `protobuf:"bytes,2,opt,name=bid,proto3" json:"bid,omitempty"`
	FetchedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=fetched_at,json=fetchedAt,proto3" json:"fetched_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatesResponse) Reset() {
	*x = GetRatesResponse{}
	mi := &file_proto_rates_v1_rates_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatesResponse) ProtoMessage() {}

func (x *GetRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rates_v1_rates_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatesResponse.ProtoReflect.Descriptor instead.
func (*GetRatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_rates_v1_rates_proto_rawDescGZIP(), []int{1}
}

func (x *GetRatesResponse) GetAsk() string {
	if x != nil {
		return x.Ask
	}
	return ""
}

func (x *GetRatesResponse) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *GetRatesResponse) GetFetchedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FetchedAt
	}
	return nil
}

type HealthcheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthcheckRequest) Reset() {
	*x = HealthcheckRequest{}
	mi := &file_proto_rates_v1_rates_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthcheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthcheckRequest) ProtoMessage() {}

func (x *HealthcheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rates_v1_rates_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthcheckRequest.ProtoReflect.Descriptor instead.
func (*HealthcheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_rates_v1_rates_proto_rawDescGZIP(), []int{2}
}

type HealthcheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthcheckResponse) Reset() {
	*x = HealthcheckResponse{}
	mi := &file_proto_rates_v1_rates_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthcheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthcheckResponse) ProtoMessage() {}

func (x *HealthcheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rates_v1_rates_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthcheckResponse.ProtoReflect.Descriptor instead.
func (*HealthcheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_rates_v1_rates_proto_rawDescGZIP(), []int{3}
}

func (x *HealthcheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_rates_v1_rates_proto protoreflect.FileDescriptor

const file_proto_rates_v1_rates_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/rates/v1/rates.proto\x12\brates.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"I\n" +
	"\x0fGetRatesRequest\x12\x1a\n" +
	"\bstrategy\x18\x01 \x01(\tR\bstrategy\x12\f\n" +
	"\x01n\x18\x02 \x01(\x05R\x01n\x12\f\n" +
	"\x01m\x18\x03 \x01(\x05R\x01m\"q\n" +
	"\x10GetRatesResponse\x12\x10\n" +
	"\x03ask\x18\x01 \x01(\tR\x03ask\x12\x10\n" +
	"\x03bid\x18\x02 \x01(\tR\x03bid\x129\n" +
	"\n" +
	"fetched_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tfetchedAt\"\x14\n" +
	"\x12HealthcheckRequest\"-\n" +
	"\x13HealthcheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x9d\x01\n" +
	"\fRatesService\x12A\n" +
	"\bGetRates\x12\x19.rates.v1.GetRatesRequest\x1a\x1a.rates.v1.GetRatesResponse\x12J\n" +
	"\vHealthcheck\x12\x1c.rates.v1.HealthcheckRequest\x1a\x1d.rates.v1.HealthcheckResponseB7Z5github.com/Lim0os/price-oracle/proto/rates/v1;ratesv1b\x06proto3"

var (
	file_proto_rates_v1_rates_proto_rawDescOnce sync.Once
	file_proto_rates_v1_rates_proto_rawDescData []byte
)

func file_proto_rates_v1_rates_proto_rawDescGZIP() []byte {
	file_proto_rates_v1_rates_proto_rawDescOnce.Do(func() {
		file_proto_rates_v1_rates_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rates_v1_rates_proto_rawDesc), len(file_proto_rates_v1_rates_proto_rawDesc)))
	})
	return file_proto_rates_v1_rates_proto_rawDescData
}

var file_proto_rates_v1_rates_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_rates_v1_rates_proto_goTypes = []any{
	(*GetRatesRequest)(nil),       // 0: rates.v1.GetRatesRequest
	(*GetRatesResponse)(nil),      // 1: rates.v1.GetRatesResponse
	(*HealthcheckRequest)(nil),    // 2: rates.v1.HealthcheckRequest
	(*HealthcheckResponse)(nil),   // 3: rates.v1.HealthcheckResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_proto_rates_v1_rates_proto_depIdxs = []int32{
	4, // 0: rates.v1.GetRatesResponse.fetched_at:type_name -> google.protobuf.Timestamp
	0, // 1: rates.v1.RatesService.GetRates:input_type -> rates.v1.GetRatesRequest
	2, // 2: rates.v1.RatesService.Healthcheck:input_type -> rates.v1.HealthcheckRequest
	1, // 3: rates.v1.RatesService.GetRates:output_type -> rates.v1.GetRatesResponse
	3, // 4: rates.v1.RatesService.Healthcheck:output_type -> rates.v1.HealthcheckResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_rates_v1_rates_proto_init() }
func file_proto_rates_v1_rates_proto_init() {
	if File_proto_rates_v1_rates_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rates_v1_rates_proto_rawDesc), len(file_proto_rates_v1_rates_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rates_v1_rates_proto_goTypes,
		DependencyIndexes: file_proto_rates_v1_rates_proto_depIdxs,
		MessageInfos:      file_proto_rates_v1_rates_proto_msgTypes,
	}.Build()
	File_proto_rates_v1_rates_proto = out.File
	file_proto_rates_v1_rates_proto_goTypes = nil
	file_proto_rates_v1_rates_proto_depIdxs = nil
}
